### ISSUE TITLE
WeUI中Grid边框

### ISSUE THREAD

**Issue by charlzyx** [charlzyx/blog#1]
weui/Grid实现
源文件 [setOnepx.less](https://github.com/weui/weui/blob/master/src/style/base/mixin/setOnepx.less);

``` less
.setTopLine(@c: #C7C7C7) {
    content: " ";
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 1px;
    border-top: 1px solid @c;
    color: @c;
    transform-origin: 0 0;
    transform: scaleY(0.5);
}
.setLeftLine(@c: #C7C7C7) {
    content: " ";
    position: absolute;
    left: 0;
    top: 0;
    width: 1px;
    height: 100%;
    border-left: 1px solid @c;
    color: @c;
    transform-origin: 0 0;
    transform: scaleX(0.5);
}
```

真▪1px边框
源文件[weui_grid.less](https://github.com/weui/weui/blob/master/src/style/widget/weui_grid/weui_grid.less)

``` less
.weui_grids {
    position: relative;
    overflow: hidden;

    &:before {
        .setTopLine(@weuiGridBorderColor);
    }
    &:after {
        .setLeftLine(@weuiGridBorderColor);
    }
}

.weui_grid {
    position: relative;
    float: left;
    padding: 20px 10px;
    width: 100% / @weuiGridColumnCount;
    box-sizing: border-box;

    &:before {
        .setRightLine(@weuiGridBorderColor);
    }
    &:after {
        .setBottomLine(@weuiGridBorderColor);
    }

    &:active {
        background-color: @itemActiveColor;
    }
}
```
